import { ReconstructionBlueprint } from '../types';

/**
 * Trigger a browser download of a string as a file.
 */
function downloadFile(content: string, filename: string, mimeType: string) {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

/**
 * Export the blueprint as a formatted JSON file.
 */
export function exportBlueprintJSON(blueprint: ReconstructionBlueprint, filename?: string) {
  const name = filename ?? `sonic-architect-blueprint-${Date.now()}.json`;
  downloadFile(JSON.stringify(blueprint, null, 2), name, 'application/json');
}

/**
 * Export the blueprint as a human-readable Markdown report.
 */
export function exportBlueprintMarkdown(blueprint: ReconstructionBlueprint, filename?: string) {
  const { telemetry, arrangement, instrumentation, fxChain, secretSauce, meta } = blueprint;

  const lines: string[] = [
    '# Sonic Architect — Reconstruction Blueprint',
    '',
  ];

  // Meta
  if (meta) {
    lines.push(
      `> **Engine:** ${meta.provider} | **Analyzed in:** ${meta.analysisTime}ms | ` +
        `**Sample rate:** ${meta.sampleRate}Hz | **Duration:** ${fmtTime(meta.duration)} | ` +
        `**Channels:** ${meta.channels}`,
      '',
    );
  }

  // Telemetry
  lines.push('## Global Telemetry', '');
  lines.push(`| Param | Value |`);
  lines.push(`| --- | --- |`);
  lines.push(`| BPM | ${telemetry.bpm}${telemetry.bpmConfidence != null ? ` (${Math.round(telemetry.bpmConfidence * 100)}% confidence)` : ''} |`);
  lines.push(`| Key | ${telemetry.key}${telemetry.keyConfidence != null ? ` (${Math.round(telemetry.keyConfidence * 100)}% confidence)` : ''} |`);
  lines.push(`| Groove | ${telemetry.groove} |`);
  lines.push('');

  // Arrangement
  lines.push('## Arrangement', '');
  lines.push('| Time Range | Section | Description |');
  lines.push('| --- | --- | --- |');
  for (const s of arrangement) {
    lines.push(`| ${s.timeRange} | ${s.label} | ${s.description} |`);
  }
  lines.push('');

  // Instrumentation
  lines.push('## Instrument Rack', '');
  lines.push('| Element | Timbre | Frequency | Ableton Device |');
  lines.push('| --- | --- | --- | --- |');
  for (const inst of instrumentation) {
    lines.push(`| ${inst.element} | ${inst.timbre} | ${inst.frequency} | ${inst.abletonDevice} |`);
  }
  lines.push('');

  // FX Chain
  lines.push('## FX Chain', '');
  lines.push('| Artifact | Recommendation |');
  lines.push('| --- | --- |');
  for (const fx of fxChain) {
    lines.push(`| ${fx.artifact} | ${fx.recommendation} |`);
  }
  lines.push('');

  // Secret Sauce
  lines.push('## Secret Sauce', '');
  lines.push(`**Trick:** ${secretSauce.trick}`, '');
  lines.push(`**Execution:** ${secretSauce.execution}`, '');

  lines.push('---', '', '*Generated by Sonic Architect*');

  const name = filename ?? `sonic-architect-report-${Date.now()}.md`;
  downloadFile(lines.join('\n'), name, 'text/markdown');
}

function fmtTime(seconds: number): string {
  const m = Math.floor(seconds / 60);
  const s = Math.floor(seconds % 60);
  return `${m}:${s.toString().padStart(2, '0')}`;
}
